### PR TITLE
Implemented code summarization evaluator

### PR DESCRIPTION
**Pull request by BrennenFa**

### CODE REVIEW

**Comment by mrhuggins03** [comment]
Hi @BrennenFa,

Sorry for the delayed response and thank you for your contribution. 

For the README, please add an input format section that describes the format of the references and predictions files, similar to the one found [here](https://github.com/SEEDGuard/SEVAL/blob/main/src/tasks/code_generation/README.md).

We are also requiring that contributors add a test script for their evaluation in the test folder. You will find a starter file for your script there. The script will test that the output of the evaluator is correct. You can find an example [here](https://github.com/SEEDGuard/SEVAL/blob/main/src/test/code_generation/test.py). We also ask that you add a "How to test" section to your README and move the data files to the test folder, e.g. answers, predictions, expected.

If you have any questions please let me know.

**Comment by BrennenFa** [comment]
Hi, I am attempting to pull the initial repository again to get access to the test folder in my local repository, but it keeps claiming that it is up to date. Is there any request I should make, any way around this, or key word I should try looking up to solve this problem? 

Thank you,
Brennen

**Comment by mrhuggins03** [comment]
Hey @BrennenFa,

This could be because you are on a forked branch from the main SEVAL repository. On your personal fork of the repository it could say something like this:

"This branch is 20 commits behind SEEDGuard/SEVAL:main"

If so you can try to use the sync fork feature. If that does not work feel free to drop another comment. I'll try to help as best I can

**Comment by BrennenFa** [comment]
That solved the issue, thank you! I pushed some new changes but had some questions. For one, my evaluator script looked like python evaluator/evaluator.py evaluator/reference.txt < evaluator/predictions.txt, which is different than the previous examples. I was wondering if there were any differences I should make as a result, and if so, if there were any key words or resources I could use to find a solution. Additionally, when I ran the test files on vs code, none of them were the same as the output file. I was wondering if you had any idea why this was. Other than that, please let me know if there are any issues with my edits and I will fix them accordingly.

**Comment by mrhuggins03** [comment]
Hey @BrennenFa, 

I do not see your changes in this pull request. It could be possible that you pushed them to your local fork but haven't committed them to this pull request?

As for how your evaluation script is run, I think I see what you are saying. The previous examples pass the predictions in as arguments while yours is redirecting the input to be from predictions. I think you can pass an argument to subprocess.run that looks like stdin=open("predictions.txt", "r"). This should pass predictions as the input. There may be some additional arguments to get this to work. I found this in the subprocess.run documentation page. You can also use chatgpt or copilot, if you have it, to help you with this code.

As for the output, do you mean that the output of the evaluator does not match the output that the CodeXGLUE repository says?

**Comment by BrennenFa** [comment]
I believe I just fixed the issue with pushing changes. When I run the test output for other folders, such as test.py  in code completion, the program says that the output does not match. I am not sure if that is an issue with my local machine, but I thought that I would mention it. Thank you for your help with the script, I will attempt to implement it shortly.

**Review by mrhuggins03 — APPROVED** [review]
Everything looks great!

**Pull request merged**
