### PR TITLE
Added Code Completion (Token level)

### PR DESCRIPTION
**Pull request by ArsalaanK7**
Added the evaluator, prediction, and answer files for the token-level code completion task (task 4) based on the implementation in CodeXGLUE.

### CODE REVIEW

**Comment by mrhuggins03** [comment]
Hi @ArsalaanK7 ,

Sorry for the delayed response and thank you for your contribution. 

Your contributions look great!

We are also requiring that contributors add a test script for their evaluation in the test folder. You will find a starter file for your script there. The script will test that the output of the evaluator is correct. You can find an example [here](https://github.com/SEEDGuard/SEVAL/blob/main/src/test/code_generation/test.py). We also ask that you add a "How to test" section to your README and move the data files to the test folder, e.g. answers, predictions, expected.

If you have any questions or suggestions please let me know.

**Comment by ArsalaanK7** [comment]
The new changes I've added should fit that, thank you for the feedback!

**Comment by mrhuggins03** [comment]
Looks great! Your code is ready to be merged and you will be added to the contributor list. Thank you!

**Review by mrhuggins03 — COMMENTED** [review]
Great job!

**Pull request merged**
