### PR TITLE
Added evaluator for code-code Clone Detection

### PR DESCRIPTION
**Pull request by EZ7051**

### CODE REVIEW

**Comment by maxxbw54** [comment]
Hi @EZ7051 , the readme file (https://github.com/SEEDGuard/SEVAL/blob/92799b302aea7f59a3adb8f04e3c713075096c97/src/tasks/clone_detection/README.md) does not look correct to me. The input of the task are a code and a collection of candidates, the output is Top K codes with the same semantic (see here https://github.com/microsoft/CodeXGLUE/blob/main/Code-Code/Clone-detection-POJ-104/README.md). Pls correct this.

**Comment by mrhuggins03** [comment]
Hi @EZ7051,

Sorry for the delayed response and thank you for your contribution. 

We are requiring that contributors add a test script for their evaluation in the test folder. You will find a starter file for your script there. The script will test that the output of the evaluator is correct. You can find an example [here](https://github.com/SEEDGuard/SEVAL/blob/main/src/test/code_generation/test.py). We also ask that you add a "How to test" section to your README and move the data files to the test folder, e.g. answers, predictions, expected.

If you have any questions please let me know.

**Comment by EZ7051** [comment]
Hi, @maxxbw54 Professor, updated the readme file, earlier I mentioned the input and output of the evaluator instead of the task, corrected it.
@mrhuggins03 Added the test.py file and moved the data files to the test folder.

**Comment by mrhuggins03** [comment]
Hey @EZ7051, 

Everything looks great! The only small thing is that we do not need the train or valid files for the evaluation. I will go ahead and delete these and then your code will be merged!

Thanks for your contribution

**Review by mrhuggins03 — COMMENTED** [review]
Looks great

**Pull request merged**
