### PR TITLE
Adding code clone detection eval script

### PR DESCRIPTION
**Pull request by gzunigapadron**

### CODE REVIEW

**Comment by mrhuggins03** [comment]
Hi @gzunigapadron ,

Sorry for the delayed response and thank you for your contribution. 

The data for your evaluator only need the predictions.txt and answers.txt. The files you added are for training the model, and we only need the data for the evaluator. You can also edit the README to describe these input files similar to how it is [here](https://github.com/SEEDGuard/SEVAL/blob/main/src/tasks/code_repair/README.md). 

We are also requiring that contributors add a test script for their evaluation in the test folder. You will find a starter file for your script there. The script will test that the output of the evaluator is correct. You can find an example [here](https://github.com/SEEDGuard/SEVAL/blob/main/src/test/code_generation/test.py). We also ask that you add a "How to test" section to your README and move the data files to the test folder, e.g. answers, predictions, expected.

If you have any questions please let me know.

**Comment by BrennenFa** [comment]
No problem! I will get to that shortly, thank you for letting me know.

**Comment by gzunigapadron** [comment]
I started moving some files and added the test script, I should be adding the last changes later this afternoon. Sorry for the little delay!

**Comment by mrhuggins03** [comment]
No problem @gzunigapadron!

**Comment by gzunigapadron** [comment]
@mrhuggins03 I believe I only need to add the expected.txt file to the test folder, but I am unsure as to how to obtain that file. I'm wondering if I could get some guidance on that, thanks!

**Comment by mrhuggins03** [comment]
@gzunigapadron You create the expected file based on the expected output from the readme on CodeXGLUE. [Here](https://github.com/microsoft/CodeXGLUE/blob/main/Text-Code/text-to-code/README.md) you can see near the end of the document an example of this.

**Comment by mrhuggins03** [comment]
The clone detection evaluation has now been implemented so I am closing this pull request. Feel free to contribute to one of the other tasks!

**Pull request closed without merging**
